package jodd.db.audit;

import java.util.Date;
import jodd.db.oom.meta.DbColumn;
import jodd.db.oom.meta.DbTable;
/**
 * TblReportModal generated by MyEclipse Persistence Tools
 */
@DbTable("tblReportModal")
public class TblReportModal implements java.io.Serializable,Cloneable {
	// Fields
        @DbColumn("fsn")
	private String fsn;
        @DbColumn("fprojectId")
	private String fprojectId; 
        @DbColumn("freportCode")
	private String freportCode;
        @DbColumn("freportName")
	private String freportName;
        @DbColumn("ffilePath")
	private String ffilePath;
        @DbColumn("femployee")
	private String femployee;
        @DbColumn("femployeeId")
	private Integer femployeeId;
        @DbColumn("ftime")
	private Date ftime;
        @DbColumn("fmemo")
	private String fmemo;
        @DbColumn("forientation")
	private Integer forientation;
        @DbColumn("forderby")
	private Integer forderby;
        
	// Constructors
	public Integer getForientation() {
		return forientation;
	}

	public void setForientation(Integer forientation) {
		this.forientation = forientation;
	}

	/** default constructor */
	public TblReportModal() {
	}

	/** minimal constructor */
	public TblReportModal(String fsn) {
		this.fsn = fsn;
	}

	/** full constructor */
	public TblReportModal(String fsn, String fprojectId, String freportCode,String freportName,
			String ffilePath, String femployee, Integer femployeeId,
			Date ftime, String fmemo) {
		this.fsn = fsn;
		this.fprojectId = fprojectId;
		this.freportCode=freportCode;
		this.freportName = freportName;
		this.ffilePath = ffilePath;
		this.femployee = femployee;
		this.femployeeId = femployeeId;
		this.ftime = ftime;
		this.fmemo = fmemo;
	}

	// Property accessors

	public String getFsn() {
		return this.fsn;
	}

	public void setFsn(String fsn) {
		this.fsn = fsn;
	}

	public String getFprojectId() {
		return this.fprojectId;
	}

	public void setFprojectId(String fprojectId) {
		this.fprojectId = fprojectId;
	}

	public String getFreportName() {
		return this.freportName;
	}

	public void setFreportName(String freportName) {
		this.freportName = freportName;
	}

	public String getFfilePath() {
		return this.ffilePath;
	}

	public void setFfilePath(String ffilePath) {
		this.ffilePath = ffilePath;
	}

	public String getFemployee() {
		return this.femployee;
	}

	public void setFemployee(String femployee) {
		this.femployee = femployee;
	}

	public Integer getFemployeeId() {
		return this.femployeeId;
	}

	public void setFemployeeId(Integer femployeeId) {
		this.femployeeId = femployeeId;
	}

	public Date getFtime() {
		return this.ftime;
	}

	public void setFtime(Date ftime) {
		this.ftime = ftime;
	}

	public String getFmemo() {
		return this.fmemo;
	}

	public void setFmemo(String fmemo) {
		this.fmemo = fmemo;
	}

	public String getFreportCode() {
		return freportCode;
	}

	public void setFreportCode(String freportCode) {
		this.freportCode = freportCode;
	}

	public Integer getForderby() {
		return forderby;
	}

	public void setForderby(Integer forderby) {
		this.forderby = forderby;
	}

}